### ISSUE TITLE
improve csv export from map explorer

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa-education#100]
Some end users are not familiar with CSV files. We don't want to export in .xls for about a million and ten reasons, but need to make it easy/automatic for people who aren't familiar with text files.

HHMI reports:
The teachers could not easily open the csv file:
- On a PC it appears that the file downloads without a file extension (this happened to me too when I tested it on a PC), but on a Mac it works fine.
- If you double click the file on a PC it tries to open in Adobe acrobat but won’t open.
- If you try to select a program to open it, excel is not an option.

SO @shaunanoordin :
- Can we ensure that that the file downloads on PCs with the extension? 
- And can we double check that the default program (in factory settings) for CSVs on PC is excel?

Hopefully this will solve the issue. If not, we can provide some help text somewhere that explains that .csv is a basic text file that can be opened by any number of programs, including excel.

**Comment by shaunanoordin** [comment]
Fixed by #102 - at least, the issue of ensuring the file is downloaded as `wildcam.csv`. We can't ensure the default apps used to open CSVs on the users' PCs; we'll need to explore XSL exports in the future.

**Comment by aliburchard** [comment]
closing this since it was fixed by #102 ( @shaunanoordin you can have the PR close the issue automatically if you reference it in the commit msg). New bugs raised though so opening new issues.
