### ISSUE TITLE
Allow students to be removed

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/wildcam-gorongosa-education#103]
Currently the Education API doesn't allow deleting entries.

**Comment by aliburchard** [comment]
@marten can you add the necessary field in the API to enable this please? Based on our post-ashmolean walk, I believe we settled on just adding a column indicating whether students are active or inactive. We still need to decide how to display this on the front end, but that gives us flexibility to either hide classifications made by inactive students or display them in a separate section.
