### ISSUE TITLE
Change default page after login to Map Explorer

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/wildcam-gorongosa-education#108]

**Comment by aliburchard** [comment]
@simoneduca I know you're flat out on the form; hoping I can ping @shaunanoordin for this.

**Comment by aliburchard** [comment]
Thinking that specifically if you click on Explore, you should go to the map page, and that if you're an educator, you should go to your classroom management page.  Hoping this is really trivial.

**Comment by shaunanoordin** [comment]
Shouldn't be a problem, I'll get a PR in by today.
- Shaun A. Noordin
  20160323

**Comment by simoneduca** [comment]
@shaunanoordin sorry I got one in already. Mind having a look and merge if ok?

**Comment by shaunanoordin** [comment]
Sure thing, sounds good to me
