### ISSUE TITLE
Promises don't work in IE11 / Promise polyfill required

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/wildcam-gorongosa-education#13]
Problem: Attempting to use any Promises in IE11 will result in an error, "'Promise' is undefined"
Diagnosis: IE11 does not support promises. Because of course.
Recommended Action: Implement a global Promise polyfill.

Encounters:
- Map Explorer (see Feature #1 ) fails to work in IE11 because the react-loadscript 1.0.2 NPM component, which is required to dynamically load the Google Maps API, requires Promises.

Recommendations:
- https://github.com/jakearchibald/es6-promise
- https://github.com/kriskowal/q

**Comment by rogerhutchings** [comment]
We've added the `babel-polyfill`, can you test @shaunanoordin?

**Comment by shaunanoordin** [comment]
[Good news everyone!](https://www.youtube.com/watch?v=g8IVI0sZ6F8) I have bad news. Also, some good news.
- Login works fine on Edge
- Classroom works fine on Edge
- Map Explorer works fine on Edge and IE11

Which is great! Technically the original issue with Promises was solved! However...
- Classrooms cannot be tested on IE11, because a dependency is malfunctioning:
  - **Logins do not work on IE11**.

**Issue**: After logging in (i.e. returning from the Login Page on Panoptes to the WGE app), the WGE app does not recognise that the user is logged in.
**Behaviour** (IE11):
- If the user is not logged in, clicking the Login link takes the user to the Panoptes Login Page. (Correct)
  - Once user submits a valid user/pass, she/he is taken back to the WGE app, but the app continues to display the Login button instead of the Logout button.
  - Consequently, the Classroom will not recognise that the user is logged in, and will not display any classes tied to the account.
- If the user has logged in, clicking the Login button will quickly bounce the user from Panoptes back to the WGE App, so it appears that the login state _is_ saved _somewhere_.

The biggest problem right now is that debugging what's wrong is nigh incomprehensible; IE11's dev console works on a per-website basis AFAIK, so when I bounce from the app to Panoptes and back to the app, I can't really follow the flow of data. I'll need to talk to @rogerhutchings to see what's the best way to proceed investigations here.

**Status**: **???** Old issue is technically resolved, but we've discovered a new one.
**Actions**: **???** Not sure if we should spawn a new issue or continue with this one.

Tested on: Chrome48/Firefox44/Edge25/IE11 on SurfacePro3+Win10

**Comment by eatyourgreens** [comment]
Can you trace the API requests in IE11 to see if the auth token is being
passed after logging in? I think the logged-in user comes from a call to
/api/me

On Wednesday, 24 February 2016, Shaun A. Noordin notifications@github.com
wrote:

> Good news everyone! https://www.youtube.com/watch?v=g8IVI0sZ6F8 I have
> bad news. Also, some good news.
> - Login works fine on Edge
> - Classroom works fine on Edge
> - Map Explorer works fine on Edge and IE11
> 
> Which is great! Technically the original issue with Promises was solved!
> However...
> - Classrooms cannot be tested on IE11, because a dependency is
>   malfunctioning:
>   - _Logins do not work on IE11_.
> 
> _Issue_: After logging in (i.e. returning from the Login Page on Panoptes
> to the WGE app), the WGE app does not recognise that the user is logged in.
> _Behaviour_ (IE11):
> - If the user is not logged in, clicking the Login link takes the user
>   to the Panoptes Login Page. (Correct)
>   - Once user submits a valid user/pass, she/he is taken back to the
>     WGE app, but the app continues to display the Login button instead of the
>     Logout button.
>   - Consequently, the Classroom will not recognise that the user is
>     logged in, and will not display any classes tied to the account.
> - If the user has logged in, clicking the Login button will quickly
>   bounce the user from Panoptes back to the WGE App, so it appears that the
>   login state _is_ saved _somewhere_.
> 
> The biggest problem right now is that debugging what's wrong is nigh
> incomprehensible; IE11's dev console works on a per-website basis AFAIK, so
> when I bounce from the app to Panoptes and back to the app, I can't really
> follow the flow of data. I'll need to talk to @rogerhutchings
> https://github.com/rogerhutchings to see what's the best way to proceed
> investigations here.
> 
> _Status_: _???_ Old issue is technically resolved, but we've discovered a
> new one.
> _Actions_: _???_ Not sure if we should spawn a new issue or continue with
> this one.
> 
> Tested on: Chrome48/Firefox44/Edge25/IE11 on SurfacePro3+Win10
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zooniverse/wildcam-gorongosa-education/issues/13#issuecomment-187996284
> .

## 

## 

James O'Donnell
email: jim@zooniverse.org
mobile: 07811 771 352
twitter: @pekingspring

**Comment by shaunanoordin** [comment]
Great news: the IE11 bug only appears on a localhost instance; attempting to login via the Zooniverse preview site works fine. Woo hoo! Arigato to @eatyourgreens for confirming this.

Issue Status: **Resolved**
Action: **Closing**

**Comment by eatyourgreens** [comment]
I've just tried logging in/out using IE 11.0.9600.17031 on Win 8.1 running in virtualbox. Logging in worked, logging out also worked but was very, very slow.
