### ISSUE TITLE
Find better position for text on home page

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/wildcam-gorongosa-education#167]
Any first time user confronted with that amount of text on the home page would think twice before coming back to the site. Either remove and find better place or significantly shorten the text.

**Comment by shaunanoordin** [comment]
<img width="1275" alt="screen shot 2016-05-25 at 15 38 37" src="https://cloud.githubusercontent.com/assets/13952701/15543968/d8a3c1b0-228e-11e6-8a0d-3d14d6634745.png">

This is what we've decided on for now. Wordy, but we're good for now.
