### ISSUE TITLE
Estimate for design time

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/wildcam-gorongosa-education#17]
Hi @jwbmartin, can you help estimate how long design for this project is going to take?

It will need:

Header
Footer
Landing page
- Classroom Admin View
  - List of classrooms (sidebar) - simple list
  - Classroom Detail (tabs)
    - Overview - dashboard view with metrics about the classroom like numbers, progress etc
    - Students - list management
    - Groups - list management again
    - Data export
- Map View
  - Data filter interface
  - Map itself
  - Create assignment

List management includes detailed pages for each student/group.

@aliburchard, @simoneduca @shaunanoordin, can you add detail / any missing views to this (as it's based on what I can fleetingly remember from two weeks ago)

**Comment by jwbmartin** [comment]
Hi @rogerhutchings if you have absolutely everything you need ready for me, without changing things halfway through the process, I could probably get something together in 2 weeks. Probably not even that long but trying to work in a bit of a cushion.

**Comment by aliburchard** [comment]
Ha, "without changing things halfway through the process" ...we'll try our best!

**Comment by simoneduca** [comment]
@rogerhutchings @jwbmartin I've added a couple of things, i.e. student list and relative detail pages.
