### ISSUE TITLE
Add ability to update teacher registration form data

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/wildcam-gorongosa-education#172]
I can see two ways to do this:
1. Make form always available. Position the `register` button next to the `new` classroom button (or somewhere appropriate). If user filled details already, pre-populate the form with them.
2. Leave things as they are atm and add a separate view where teachers can edit the form data. E.g. a modal that opens on clicking a details link, placed, say, under the logout button.

1 is quicker than 2.

@aliburchard thoughts?

**Comment by eatyourgreens** [comment]
The register button should vanish for registered users, otherwise you register then think something's gone wrong because you're still being prompted to register.

Option 2 can reuse the same form component, right? No point in building a completely new form if we've already got one that we can use.

**Comment by simoneduca** [comment]
I like option two better and, sure, we can use the same form.

**Comment by simoneduca** [comment]
@rogerhutchings and @eatyourgreens I've pushed some changes

**Comment by aliburchard** [comment]
Lower priority than other sprint milestones.

**Comment by eatyourgreens** [comment]
I think we can drop this completely.

**Comment by simoneduca** [comment]
👍

**Comment by aliburchard** [comment]
yeah, alright, let's close this thing.
