### ISSUE TITLE
Ability to remove students from classrooms

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/wildcam-gorongosa-education#175]
Relies on updating education-api. Add 'remove' button on the student table under students tab. Once a student is removed it simply won't be returned in the next api call. If needed, we'll think about preventing a student keeping joining a classroom, after being removed from it, given they’d still have the join link.

**Comment by eatyourgreens** [comment]
Should we have a boolean flag on classrooms to indicate if they are open/closed? Teachers could flip the status somewhere in the UI, and the join link should only be honoured if the classroom is set to open.

**Comment by simoneduca** [comment]
Closed via zooniverse/wildcam-gorongosa-education#199
