### ISSUE TITLE
Sync classification data to classroom pages and map (and discuss timing with Marten)

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/wildcam-gorongosa-education#177]
This needs breaking down properly. Whether it's nightly scheduled tasks will do this and also if any warning needs to be given to users about classification number, etc.

**Comment by shaunanoordin** [comment]
Update:
- Sync Classifications to Teacher & Student Classrooms: **DONE**
- Sync Classifications to CartoDB: _not yet_

**Comment by shaunanoordin** [comment]
I'm splitting off the incomplete "Sync Classifications to CartoDB" feature into a different issue and closing this particular one; as far as the Milestone is concerned, Classifications in Classroom is good to go.
