### ISSUE TITLE
Add "last updated at" field for when the classroom/student counters were updated

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa-education#197]
Since counters are currently updated every 24 hours (or will be once the sync is live), folks are noticing a mismatch between the classifications made and the number displaying next to their name.

As discussed yesterday on the sofas, the ultimate solution will be to listen to the event stream, but that's a low priority behind a lot of other back end work, so we think that adding a "this counter was updated X hours ago" field next to the counter would go a long way to alleviating the confusion. 

I suspect @marten needs to add this stamp to the api and @simoneduca needs to grab it for display?

**Comment by simoneduca** [comment]
This has been superseded by implementing real-time counters.
