### ISSUE TITLE
How can we show student classifications filtered by classroom?

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/wildcam-gorongosa-education#200]
Here's an idea. Assignments have unique workflow ids, so we can always count classifications made through assignments. We could suggest to educators that in order to have meaningful counters values they should invite students to classify via assignments. Of course, an assignment could be the entire Wildcam subject set. To avoid counters to be skewed, I think we wouldn't want to include classifications made by students just by going to the site (i.e. not via assignment).
I'm probably missing something but this is a starting point. See #198 for background info. 
Thoughts?

**Comment by aliburchard** [comment]
I think this makes a _lot_ of sense. Maybe down the line we can add an easy route to "the whole wildcam subject set" as an assignment (make a default assignment)?

**Comment by simoneduca** [comment]
@aliburchard yes I like the idea of a default assignment.

**Comment by simoneduca** [comment]
Closing; I'll move the idea of a default assignment to Future Plans milestone.
