### ISSUE TITLE
Specs: Creating New Assignments (and Linking Subject Sets to Them)

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/wildcam-gorongosa-education#226]
Feature/User Story: Teacher wants to create a new Assignment. Obviously, the new Assignment needs Subjects attached to it.
### Method 1: Start at the Classroom->New Assignment Page

![wildcamlab-assignment-page1](https://cloud.githubusercontent.com/assets/13952701/16497741/6ec63696-3ef0-11e6-90ff-bdee7cf0a2ad.jpg)

If the user is a Teacher who just wants to create Assignments for her class, she should be able to have a straightforward flow from her Classrooms "control centre".
1. Teacher goes to an existing Classroom and chooses to create a New Assignment.
2. Teacher is taken to the New Assignment form.
3. After filling in all the fields, Teacher is prompted to 'create Subject Set' 
   - (Alternatively, Teacher can select from previously created Subject sets from a dropdown)
4. Clicking 'crete Subject set' takes the Teacher to the Map Explorer.
5. Teacher sets filters on the Map Explorer then clicks on the new 'create new Subject Set for Assignment' button **(new feature to be built)**
6. Teacher is then taken back to the previous New Assignment form, with the previous fields already filled, and the newly created Subject Set listed.
7. Teacher can now click the 'Create' button to confirm the creation of the Assignment.

Technical notes:
- When navigating out of the New Assignment form, the filled-in fields would need to be stored as a temporary object. (e.g. "Redux.store.teachers.TEMPNEWASSIGNMENT")
- When returning to the New Assignment form from the Map Explorer, the previously stored fields would be recalled to repopulate the form.
- Similarly, the newly created Subject Set would need to be stored somewhere, e.g. Redux.store.teachers.TEMPSUBJECTSET.
### Method 2: Start at the Map Explorer Page

![wildcamlab-assignment-page2](https://cloud.githubusercontent.com/assets/13952701/16497748/782242de-3ef0-11e6-8435-46ddc118d91a.jpg)

If the Teacher wants to explore the Map Explorer, she should be able to "save" the Subject Sets she finds interesting, then later use those sets in the Assignments she creates.
1. Teacher goes to the Map Explorer (Teacher->Data)
2. Teacher sets filters on the Map Explorer then clicks on the new 'save Subject Set' button **(new feature to be built)**
3. Teacher will then be taken to the Subject Sets admin page. **(new feature to be built)**
4. Teacher can then, at any time, manually navigate to the Teacher->Classrooms page to create a new Assignment.
5. In the New Assignment Form, all saved Subject Sets would be listed as a dropdown, alongside the 'create Subject Set' button from Method 1.

Technical notes:
- **The list of "saved" Subject Sets needs to be persisted somewhere.** Most likely, this will be a new feature for the Education API.
- This will require a new Subject Sets admin page for viewing/editing/deleting the Teacher's list of "saved" Subject Sets.

Q: Method 1's Step 5 looks suspiciously like Methods 2's Step 2. How would the code know when the Teacher just came from the New Assignment form (i.e. Method 1) or just checking out the Map Explorer first (i.e. Method 2)?
A: When Redux.store.teachers.TEMPNEWASSIGNMENT isn't `null`, the Teacher is coming from Method 1. Otherwise, Method 2.

cc: @simoneduca and @aliburchard

**Comment by simoneduca** [comment]
That makes sense, @shaunanoordin. Thanks for summarising our earlier chat.
This can only start being implemented when #225 is merged.
@marten I was thinking to store the subject sets under `teachers`, on the same level as `classrooms`; unless you can think of a more sensible place.

**Comment by marten** [comment]
@simoneduca Oh, I was thinking we were going to do it more along the lines of Option 1: create an assignment (do a `POST /assignments` without passing in subject ids). When looking at a saved assignment, there's a button to jump into the map explorer, find subjects, and do an update call (`PUT /assignments/:id`) to add the subjects. So the education frontend doesn't know about "subject sets", just that an assignment has a list of subject ids.

I've only quickly scanned @shaunanoordin's post, but what are the tradeoffs between approaches?

**Comment by simoneduca** [comment]
Somehow I didn't receive a notification for this message, sorry for the delay @marten.
Right, I still think your suggestion is the easiest, but not necessarily the smoother in terms of ux. For instance: do we send the assignments created without subjects to students or should we wait?

The two approaches Shaun sketched are compatible, so no trade offs between them really. The idea is to make it as easy as possible to create assignments.

However, I am still in favour of sticking with just one workflow for now and enhance later.
Thoughts?

**Comment by simoneduca** [comment]
@aliburchard did you have a chance to look at this thread?

**Comment by aliburchard** [comment]
Talked about it with shaun and marten the other day, and based on our convo yesterday, I agree that we should go with one workflow for now and enhance later. My impression from @shaunanoordin and @marten is that the pieces are already in place for the first approach (start from an assignment, bounce to the map page, then bounce back). It's not quite as smooth perhaps as the second, but I think it's a good place to start and we're pretty well set up for it.
