### ISSUE TITLE
package.json needs fixes - PJC incompatible after 2.2.1, staging-vs-production confusion

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/wildcam-gorongosa-education#231]
`package.json` needs to be modified so:
*`"deploy-production": "npm run build && publisssh dist zooniverse-static/lab.wildcamgorongosa.org"` => `"deploy-production": "NODE_ENV=production npm run build && publisssh dist zooniverse-static/lab.wildcamgorongosa.org"`
- `"panoptes-client": "^2.2.1",` => `"panoptes-client": "2.2.1",`

Why?
- On PJC 2.5.1 and 2.5.2, after logging in, we get the `401 Unauthorised` error from zooniverse.org/oauth/token. Sticking with 2.2.1 seems to fix this for the time being.
- Without explicitly stating `NODE_ENV` in package.json, the build will take _any default NODE_ENV on the dev's programming environment._ So, e.g., when @shaunanoordin attempts to deploy to production from his machine, and his machine environment has NODE_ENV=staging, lab.wildcamgorongosa.org will think it's on staging.

This is madness.

**Comment by simoneduca** [comment]
Closed via #266
