### ISSUE TITLE
Workflow for Assignments serve same Subjects, in order (not randomised)

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/wildcam-gorongosa-education#232]
Issue: in OG WildCam Gorongosa, when a students switches to an Assignment workflow, it appears that Subjects are served to users in a specific order (i.e., the subjects aren't served randomly.)

Analysis:
- Two things I suspect: 1. there may be a Panoptes setting that sets random Subjects on/off, and 2. it may have something to do with the size of Subject Sets created for the tested Assignments.
- This has been confirmed on Assignment (production-)ID 1: "Lion Assignment" where a user, `zootester1` would always receive a specific set of Lion images, in order, whenever she accesses/refreshes the website.
- The problem can be replicated by using `zootester2` on the Lion Assignment.
- Seen images aren't marked as such when revisited.
- Strangely, Assignment (production-)ID 2: "Baboon Assignment" has a random chance of randomisation. (Sometimes it's random, sometimes it's in order.)
- Status: WTF?

CCing @aliburchard into this and @marten . This is a non-blocking issue that can be handled after everyone's back from a break. This issue may need to be shunted into EduAPI or OGWG.

**Comment by marten** [comment]
Uhm, well the Panoptes DB has no classifications for any workflow that's not 338 (the original one). Are they getting submitted to the correct workflow id?

/cc @rogerhutchings

**Comment by simoneduca** [comment]
Yep, this is the problem https://github.com/zooniverse/wildcam-gorongosa/blob/552d94d545dfb343842e9198c4d852c0eb667d63/app/stores/classification-store.coffee#L34. Roger's on it.

**Comment by simoneduca** [comment]
Closed via https://github.com/zooniverse/wildcam-gorongosa/pull/229
