### ISSUE TITLE
Work out what's going wrong with newer versions of PJC 

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/wildcam-gorongosa-education#233]
As per #231 - newer versions of PJC are producing auth errors. It _appears_ to be working when we pin the version to 2.2.1, but this is sub-optimal.
- [ ] Work out why newer versions of PJC break auth
- [ ] Add the caret back in front of `panoptes-client` in `package.json` to allow newer versions

**Comment by simoneduca** [comment]
I had `2.5.2` installed locally and auth was working fine. Can we confirm that the problem is just on production?

**Comment by rogerhutchings** [comment]
are you hitting the staging or production api?

**Comment by simoneduca** [comment]
staging.

**Comment by simoneduca** [comment]
So we faced this issue again. I forgot to check what version of the client I had locally (`2.5.2`) and deployed to production. Result: authentication was broken. It should have been `2.2.1`.
