### ISSUE TITLE
Remove old student classroom list stuff

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/wildcam-gorongosa-education#239]
Superseded by the assignments view

**Comment by rogerhutchings** [comment]
Has this been done yet? I'm pretty sure I hadn't removed the old containers / components

**Comment by simoneduca** [comment]
Oops, my bad. I just assumed they were already removed, sorry.

**Comment by rogerhutchings** [comment]
Mind doing it?

**Comment by simoneduca** [comment]
Sure, I was hesitating because it seemed reasonable to show students details of the classrooms they belong to; but we can always add that later.

**Comment by rogerhutchings** [comment]
We talked about this while you were away - students won't be members of many classrooms, and they don't really need that information, they just need their assignments

**Comment by simoneduca** [comment]
Fair enough. On my to-be-removed list I've got so far:
- `StudentClassroomsContainer`
- `StudentClassroomContainer`
- `StudentClassroom`
- `StudentClassroomsSidebar`
- `StudentOverview`

Did I miss/add any/too many?

**Comment by rogerhutchings** [comment]
Any styles and such

**Comment by simoneduca** [comment]
There's none specific to them.

**Comment by simoneduca** [comment]
The routing needs adjusting too. Did you have any thoughts on what to display when a student joins a classroom?

**Comment by rogerhutchings** [comment]
We can take them back to the assignments list. We could add an [alert](http://getbootstrap.com/components/#alerts) as well

**Comment by simoneduca** [comment]
The PR I've just submitted takes them to the map, which may be confusing. I think redirecting to the assignment list is equally confusing without messaging, so I'll add that in.
