### ISSUE TITLE
View assignments (students) MVP

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa-education#257]
@simoneduca just reminding myself/nailing down what we said for student assignment page:

Student view should display:
- [x] Classroom Name (big header)
- [x] Assignment name (smaller header)
- [x] Assignment description (which was generated by the teacher)
- [x] Assignment due date
- [x] Progress (the number of classifications they've made out of the total classifications required)
- [x] Button to download their raw assignment data

Am I forgetting anything?

**Comment by simoneduca** [comment]
@aliburchard just waiting for PR to be merged.

**Comment by simoneduca** [comment]
Closed via #264
