### ISSUE TITLE
Update OGWG to tell students they've finished an assignment

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa-education#265]
We basically need a way to tell students they've finished classifying the # of images required on an assignment. This is a pretty high priority, but fixing https://github.com/zooniverse/wildcam-gorongosa/issues/230 could buy us some time to figure out what we tell students to do _after_ they've finished their assignment.

**Comment by shaunanoordin** [comment]
Closed by zooniverse/wildcam-gorongosa#245
