### ISSUE TITLE
Let Panoptes store group IDs

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/wildcam-gorongosa-education#27]
Upon post-processing (ClassificationLifecycle) a classification in Panoptes, Panoptes should add to the metadata a list of the groups the user is currently in.

**Comment by rogerhutchings** [comment]
@marten is this one done?

**Comment by marten** [comment]
Ah, yes. Fixed in https://github.com/zooniverse/Panoptes/pull/1660
