### ISSUE TITLE
CSVs downloaded from assignments page are old format

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa-education#276]
Not sure if this falls to @shaunanoordin or @simoneduca but the csvs downloaded from the assignments page use the old headers instead of the ones you get if you download from the map explorer.

**Comment by aliburchard** [comment]
@shaunanoordin we just chatted about this this morning. We should make the aggregated data download as csv easy mode. We need to think about what format the raw classification data (i.e. "my data") should take. I suspect it should be as close to the aggregated data format as possible, but will discuss with Bridget.

**Comment by simoneduca** [comment]
Closed via #286
