### ISSUE TITLE
Joining a classroom when not logged in does not fail

### ISSUE THREAD

**Issue by marten** [zooniverse/wildcam-gorongosa-education#288]
If you're not logged in, and go to a join-classroom page, you will see the "Join Classroom!" button. 

Clicking that button will take you to the map view (suggesting it worked), but the join-request made to the server will have failed (because non-logged-in people cannot join a classroom, server responds with a 403 Forbidden status code).

Expected result: lab does not show a join button, but instead instructs that you need to log in first.

**Comment by simoneduca** [comment]
Cool, thanks @marten.
