### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/wildcam-gorongosa-education#3]
Simple view showing login buttons on a suitable background. There are two buttons: 'Teachers' and 'Students'. There is also a header with the application name and a login link.

**Comment by aliburchard** [comment]
In my head, I want some exciting visualization (maybe just displaying a map) that makes people want to sign in, join up, whatever, but I think this is good for now. 

What's the difference in what users see if they are logged into their zooniverse account or not?

**Comment by simoneduca** [comment]
I'm not sure. It'd probably make sense to redirect them to Zoo login page if they weren't signed in already, no?

**Comment by aliburchard** [comment]
I don't think so - we still want them to know this is a thing. What about how the project builder does it? https://www.zooniverse.org/lab - basically, you've got a teaser of the awesomeness you'll uncover if you log in. And by clicking on the sign in link, you don't actually have to leave the page to sign in.

**Comment by rogerhutchings** [comment]
To do OAuth, we need to take them away from the page and come back anyway :/
