### ISSUE TITLE
Add in filter controls for Map explorer

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/wildcam-gorongosa-education#50]

**Comment by shaunanoordin** [comment]
This is a subset of #1 Map Explorer

For the Alpha, the following filters are required:
- Species
- Habitat
- Season
- Date range

As per Slack convo:

```
Ali Swanson Feb 3rd at 6:06 PM
@shaun.a.noordin: key filters for alpha should include species, habitat, season and maybe date-range.
```

NOTE:
- While @aliburchard pointed out some really well-built control plugins from CartoDB's [deep-insight.js](https://github.com/CartoDB/deep-insights.js), I'm aiming to build something more basic for the Alpha release on Fri 26 Feb 2016.

Apologies, given the time required for me to integrate the plugins, I'll need to wait for the Beta development period.
