### ISSUE TITLE
Add metadata to classroom

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/wildcam-gorongosa-education#51]
> Additional metadata fields like "subject", maybe "school" and "description"

From #5 via @aliburchard

**Comment by simoneduca** [comment]
@marten can we do this please?

**Comment by marten** [comment]
D'oh, I added the fields and they're accepted on the POST request, but just not serialized back. Will be fixed in next deploy

**Comment by simoneduca** [comment]
cool, thanks
