### ISSUE TITLE
Add a Feedback Form to WGE

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/wildcam-gorongosa-education#60]
Required functionality:
- Alpha/Beta users must be able to provide feedback regarding project, easily.

**Comment by aliburchard** [comment]
@mrniaboc pinging you for creating this :)

**Comment by aliburchard** [comment]
Draft form up here: https://docs.google.com/a/zooniverse.org/forms/d/1Cx4LDXevyqZZheB_EupVRxd7jCzpoH-m8j494cyNNfc/edit

**Comment by shaunanoordin** [comment]
Thanks @aliburchard ! Some comments:
- Opening statement says `Thanks for helping us test our newest proposed project! This project was not built by the Zooniverse. It was entirely created by researchers using our project builder, and your feedback will be vital to us as we decide whether to promote it as an official Zooniverse project.` which seems incongruous. May I suggest something along the lines of: `Thanks for helping us test our Education Portal for Wildcam Gorongosa! This project is still in its early stages, and we would like your feedback to shape this educational tool. We want to see how the scientific/research data from Wildcam Gorongosa can be used in classrooms, so we are extremely interested in understanding how teachers & students use the Education Portal.`
- `Why do you want to use Wildcam in your classroom?` could be better phrased as `Wildcam Gorongosa Education Portal` or something more descriptive than `Wildcam`. It might not matter for the first few testers who know what Wildcam is, but may matter for future form-fillers.
- Suggestions for two questions to wrap up the form:
  - Would you recommend this Education Portal to a student/other teachers? (Y/N)
  - If no, please share why so we can better understand how we can improve the portal. (textbox)

**Comment by aliburchard** [comment]
Thanks @shaunanoordin! I've finalized the text for this. Would be nice to put up a link to it as another tab, but we can also just send it around in the email.
