### ISSUE TITLE
Subgroups - Assignments

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/wildcam-gorongosa-education#7]
It is still TBD whether subgroups of classes (classes are groups) will be a incorporated within assignments or be a separate tab.

![img_4464](https://cloud.githubusercontent.com/assets/8989606/12144718/95ab5d44-b481-11e5-9bcc-b6397d408a96.JPG)
![img_4465](https://cloud.githubusercontent.com/assets/8989606/12144717/95aaa156-b481-11e5-8e0a-157d7943e689.JPG)

**Comment by simoneduca** [comment]
The team has reached agreement on how to implement **assignments**. Here's how:

An assignment boils down to a link. The key part of an assignment link is a workflow id. This new workflow is created by cloning the wildcam workflow and assign a different id to it.

The cloned workflow has a specific subject set attached to it, which is determined by the educator using the map filters in the Explorer UI. The educator also chooses the students who will receive the assignment.

Students see their assignments when they log in. The assignment link takes them to [Wildcam](wildcamgorongosa.org) where they have access to a specific subject set.

~~Use case:~~

~~1. Within Explorer ui, educator creates a subject set with filters~~
~~2. Within Admin ui, educator creates an assignment by:~~
  ~~1. choosing a classroom~~
  ~~2. choosing the subject set previously created (or a different one if more exist)~~
  ~~3. choosing the students of that classroom to send the assignment to~~

**Comment by aliburchard** [comment]
Just to note that the assignment link takes the students to something that looks exactly like wildcam, but will have a different workflow ID (so I suppose a different URL). 

Given that the classifications will be on existing subjects on a new workflow, we'll need to figure out how to add them back into the overall wildcam gorongosa dataset so they contribute to the project data. We can do this on the back end later.

**Comment by simoneduca** [comment]
@aliburchard yes the url for assignments would look something like `http://www.wildcamgorongosa.org/#/classify/1234`.
Adding the classifications done within an assignment to the main subject set can be done by running a nightly job or something like that.
