### ISSUE TITLE
Teachers input profile/account metadata

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa-education#73]
When teachers log into the portal for the first time, they should be prompted to enter certain metadata. They can also edit/add this later. 

This metadata should include:
- School name
- Grade(s) taught
- Subject(s) taught
- Data use agreement

**Comment by aliburchard** [comment]
@simoneduca we can be a bit more flexible as to how this is implemented. We should brainstorm how to balance the ability of users to jump in easily, with a real need for HHMI to collect this data.

**Comment by aliburchard** [comment]
We could, for example, ask folks to answer these questions before creating their first classroom, instead of when they first land on the site.

Also, HHMI has indicated they're fine with something as simple as a google doc, but that they would like this information to be required before people can create classrooms. I think we need to discuss this internally before implementing.

_note_ the questions they've sent are pinned in slack

**Comment by simoneduca** [comment]
Closed via #128.
