### ISSUE TITLE
To Consider: Should we limit how many entries a Teacher/Student can download in a CSV?

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/wildcam-gorongosa-education#81]
Reflecting on the Export CSV feature introduced in PR #80

Questions:
- When the user uses the "Export Wildcam Gorongosa Data as CSV" feature, should we put any limits on how much data the user can download? If yes/no, why?
- If yes, what limits do we want to put? And do we want to make it a rule that "you can only download the 1000 _most recent_ classifications"?
- Should there be different restrictions for teachers and students? What about researchers? (Assuming that is a separate category.)

Technical Considerations:
- The only technical question is, say, will a hundred students/teachers each downloading 10 million classifications strain the CartoDB system?
- Currently, we have a very simple 1000 item limit that's very easily enforced with `"SELECT * FROM wildcam_gorongosa LIMIT 1000"`. Changing the code is relatively simple, and yes, it's possible to allow students/teachers to self-regulate (i.e. set their own limits) if we think that's a good idea.

@aliburchard , please share your thoughts, especially on the user & researcher perspective, and please ping anybody else who can contribute their experience on the matter.

**Comment by aliburchard** [comment]
I think we'll ultimately want a way for users to define how many classifications they want to download.

Providing different options based on user role might be nice down the line, if we can get to it (and I can see potential use cases for researcher v non-researcher), but I don't think it's a priority.

**Comment by shaunanoordin** [comment]
Update
- Current answer is: nope, no limits.
- Rationale: With our experiments using "realtime" CartoDB data updates, we've seen that CartoDB can handle the requests we're sending it, so... yeah, no need to worry about limits right now.
- Notes for future reference: at the moment, using Map Explorer, a user can **at most** download an uncompressed CSV file containing 40,388 results at approx 12MB. This seems manageable, but we'll want to revisit if the max number of possible results grow.
