### ISSUE TITLE
Wildcam Pre-assignments Sprint (aka Hoisin Duck Release)

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa-education#89]
I'm creating this list of near-term (ideally pre-Chicago) priorities. @shaunanoordin and @simoneduca I will let you guys create the actual issues for the milestone, this is just to put the overview list in a shared place we can refer to.
- [x] Fix teacher registration form to fixed answers only
- Ability to
  - [x] ~~update registration form data~~ (Descoped)
  - [x] update classroom descriptions
  - [x] delete classrooms
  - [x] remove students from classrooms
- [x] Display # classrooms and # classifications to student overview
- [x] Sync classification data to classroom pages and map (and discuss timing with Marten)
- [x] Review text on landing page (last thing!)
- [x] Add link to this from main wildcamgorongosa.org page
- [x] optimize panoptes user group fetching (this is one for @marten)

**Comment by shaunanoordin** [comment]
Woo hoo, we're done here! The Hoisin Duck is fully cooked!

**Comment by aliburchard** [comment]
🎆 🎉 🎈
