### ISSUE TITLE
Link aggregated wildcam data to carto for "the world" display

### ISSUE THREAD

**Issue by aliburchard** [zooniverse/wildcam-gorongosa-education#95]
In the me/my group/the world display, "the world" should be linking to aggregated data. (And displaying aggregated data is anticipated to be one of the key use cases for the map.

@shaunanoordin we'll need to convert @ggdhines aggregation script to ruby and get it sitting next to your csv exploder wherever @marten says they should sit.

**Comment by shaunanoordin** [comment]
Closed by #131
