### ISSUE TITLE
Get an "Official Zooniverse" CartoDB Account

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/wildcam-gorongosa-education#97]
- Currently, the CartoDB account we're using for WildCam Labs is `shaunanoordin-zooniverse`, viewable at https://shaunanoordin-zooniverse.cartodb.com/me . This was always intended to be a dev/testing account.
- To go into production, we need to talk to the CartoDB team to get an **official** `zooniverse` account on CartoDB. Notably, this means:
  1. We need to create a new account tied to a general 'zooniverse team' e-mail
  2. We need to get the standard 250MB database size limit (for free accounts) increased.

**Comment by eatyourgreens** [comment]
There's a CartoDB account with username `the-zooniverse`. The password is stored with all the other zoo passwords. It might be a free account with limited storage though.

**Comment by aliburchard** [comment]
oh sweet, well that's a start! at least we don't have to create a new one, just talk to Stuart about bumping the limit. thanks!

**Comment by shaunanoordin** [comment]
Awesomeness, thanks @eatyourgreens!
