### ISSUE TITLE
Create Aggregation Data for WildCam-CartoDB

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/wildcam-gorongosa-education#98]
- We've solved the issue of getting WildCam Gorongosa Classifications data to CartoDB.
- Now we need to do the same for Aggregation data.

Hey @shaunanoordin, since you learnt Ruby last week, it's time to learn more Python now!
- Go to the https://github.com/zooniverse/aggregation repository
- ~~Look at [csv_output.py](https://github.com/zooniverse/aggregation/blob/master/engine/csv_output.py) and anything that does `survey` tasks.~~
- Look at [survey_aggregation.py](https://github.com/zooniverse/aggregation/blob/master/engine/survey_aggregation.py)
- Look at [gorongosa_aggregation.py](https://github.com/zooniverse/aggregation/blob/master/engine/gorongosa_aggregation.py)
- Get that code running in Ruby and plonk it into the data flow set up by @marten .
- Don't forget to add Pielou's evenness index.

**Comment by aliburchard** [comment]
Hey @shaunanoordin should we close this since we're sticking with the existing python scripts?

**Comment by shaunanoordin** [comment]
That is extremely correct. New plan: we stick with Python!
